### ISSUE TITLE
Dropdown always shows value "Checkout"

### ISSUE THREAD

**Issue by ch109** [trustedshops-public/connect-app-eventslib#32]
### What happened?

- "Send review invites" > Dropdown:
        - Dropdown always shows "Checkout" plus my values
        -  I have not specified the value "Checkout"
        - My presumption is that it is hard-coded for presentation purposes

### Problem description

Dropdown always shows "Checkout"

### Expected behaviour

Dropdown only shows values I specify via payload of event `EVENTS.SET_AVAILABLE_ORDER_STATUSES`.

### Actual  behaviour

Dropdown always shows "Checkout" plus my values (see screenshot below).

<img width="1099" alt="Screenshot 2023-11-20 at 13 13 44" src="https://github.com/trustedshops-public/connect-app-eventslib/assets/20778129/446e7c8b-b3af-47de-9344-d143d36cef7d">

### Steps to Reproduce

I use it according to instructions from the [README.md](https://github.com/trustedshops-public/connect-app-eventslib#available-order-statuses-eventsget_available_order_statuses--eventsset_available_order_statuses)

```javascript
const availableOrders = [
  { name: 'Awaiting Payment', ID: '1', event_type: 'order_status_from_nameOfSystem' },
  { name: 'Payment accepted', ID: '2' },
  { name: 'Processing in progress', ID: '3', event_type: 'order_status_from_nameOfSystem' },
  { name: 'Shipped', ID: '4' },
  { name: 'Delivered', ID: '5' },
  { name: 'Canceled', ID: '6' },
  { name: 'Refunded', ID: '7' },
];

const unregisterEvents = registerEvents({
  // ...
  [EVENTS.GET_AVAILABLE_ORDER_STATUSES]: (event: {
    action: "TS_GET_AVAILABLE_ORDER_STATUSES";
    payload:  {id: string, eTrustedChannelRef: string, salesChannelRef: string }
  }) => {
    dispatchAction({
      action: EVENTS.SET_AVAILABLE_ORDER_STATUSES,
      payload: availableOrders,
    });
  },
  // ...
});
```

### References

[README.md for v2.0](https://github.com/trustedshops-public/connect-app-eventslib#new-events-in-version-20)

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by eburck** [comment]
Hello @ch109 ,

we populate the object on purpose with the default:
 { name: 'Checkout', ID: 'checkout', event_type: 'checkout' }

Why is that?
With the Trustbadge embedded on Thank-You page there is automatically the status "Checkout" available to trigger a review invite. 
If a user selects "Checkout", Trustbadge takes over to send event to eTrusted. There is no need for an additional event call from the base layer.

**Comment by eburck** [comment]
Improvement of  documentation needed.
