### ISSUE TITLE
"Send review invites": Click on "Save" button shows infinite loading spinner

### ISSUE THREAD

**Issue by ch109** [trustedshops-public/connect-app-eventslib#33]
### What happened?

- "Send review invites" > Click on "Save" button
  - It works the first time, after that every time I click "Save", I see a loading spinner which does not disappear 
    - The whole site is blocked until I reaload it

### Problem description

- "Send review invites" > Click on "Save" button
  - It works the first time, after that every time I click "Save", I see a loading spinner which does not disappear 
    - The whole site is blocked until I reaload it

### Expected behaviour

- "Send review invites" > Click on "Save" button
  - Should save the settings
  - Then the loading spinner should disappear

### Actual  behaviour

- "Send review invites" > Click on "Save" button
  - It works the first time, after that every time I click "Save", I see a loading spinner which does not disappear 
    - The whole site is blocked until I reaload it
  - A HTTP-Request is done with a resulting error with code 409
    - Payload: 
        ```json
        {
            "active":true,
            "name":"order_status_from_shopify"
        }
        ```
    - Response:
        ```json
        {
            "Error": "Invalid request",
            "ErrorDescription": "An event-type with the given name already exists!"
        }
        ```
 
 - Screenshots:
 
<img width="1906" alt="Screenshot 2023-11-20 at 13 16 20" src="https://github.com/trustedshops-public/connect-app-eventslib/assets/20778129/93713925-bb4c-4a7f-932a-f73a3834f5bc">

<img width="1079" alt="Screenshot 2023-11-20 at 13 17 08" src="https://github.com/trustedshops-public/connect-app-eventslib/assets/20778129/5cad2703-27fb-4516-a0a1-a0c369fffb64">

<img width="936" alt="Screenshot 2023-11-20 at 13 17 30" src="https://github.com/trustedshops-public/connect-app-eventslib/assets/20778129/ede4b2fb-92dd-4f87-9e53-b73825ad2bed">

<img width="1044" alt="Screenshot 2023-11-20 at 13 17 46" src="https://github.com/trustedshops-public/connect-app-eventslib/assets/20778129/774f385b-bec7-4349-b3e9-d7fa9287e605">

### Steps to Reproduce

I set up the events according to the [README.md for v2](https://github.com/trustedshops-public/connect-app-eventslib#save-order-statuses-eventssave_used_order_statuses)

### Important Factoids

- It works the first time, after that every time I click "Save", I see a loading spinner which does not disappear 

- The response could be an important clue:

```json
        {
            "Error": "Invalid request",
            "ErrorDescription": "An event-type with the given name already exists!"
        }
```
- Can you implement something like an "upsert" ?
  - Insert the value if it's not there
  - Update the value if it's already there

### References

[README.md for v2](https://github.com/trustedshops-public/connect-app-eventslib#new-events-in-version-20)

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by eburck** [comment]
Hello @ch109 ,

this looks very much like you are providing an event-type name with a different upper/lower case of an event-type that already exists.

Please do not state an event_type attribute inside object Available_Order_Statuses.
It is actually not needed, as connector itself will take care of event-types: checking if already exists, creation and settings.
Connector will hand back the event-type name to be used for POST /events in attribute 'name' of  SAVE_USED_ORDER_STATUSES.activeStatus.

Anyway, we need to handle the reported error "An event-type with the given name already exists!" when trying to create a new event-type.
